# Your workflow name.
name: Deploy to Cyclic.sh

# Run workflow on every push to the main branch (update as per Cyclic.sh requirements).
on:
  push:
    branches: [main]

# Your workflow jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Build and Push a Docker container to Cyclic.sh
        uses: cyclic-sh/github-action@v1  # Update with the appropriate Cyclic.sh action.
        with:
          # Below you must provide variables for your Cyclic.sh deployment.

          # Add any required environment variables for Cyclic.sh
          # For example:
          ENV_VAR_NAME: ${{ secrets.ENV_VAR_NAME }}

          # (Optional, default: "./")
          # Dockerfile directory.
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_build_options: "--no-cache"

          # (Optional, default: "")
          # Additional options of docker push command.
          docker_push_options: ""

          # (Optional, default: "")
          # Additional options of docker run command.
          docker_run_options: ""

          # (Optional, default: "")
          # Additional options of docker login command.
          docker_login_options: ""
